# Generated by Django 4.2.5 on 2023-09-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='condominio',
        ),
    ]
