# Generated by Django 4.2.5 on 2023-09-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_alter_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='numero_chamado',
            field=models.PositiveIntegerField(blank=True, default=1, editable=False, unique=True, verbose_name='Número de Chamado'),
        ),
    ]
