# Generated by Django 4.2.5 on 2023-09-11 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0005_ticket_numero_chamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numero_chamado',
            field=models.PositiveIntegerField(blank=True, editable=False, unique=True, verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Andamento'), ('fechado', 'Fechado')], default='aberto', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assinado Por'),
        ),
    ]
