# Generated by Django 4.2.5 on 2023-09-20 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0011_alter_ticket_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comentario',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comment',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='titulo',
        ),
    ]
