# Generated by Django 4.2.5 on 2023-09-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_rename_category_categoria_rename_comment_comentario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='descricao',
        ),
    ]
