# Generated by Django 4.2.5 on 2023-11-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0015_ticket_comentario_fechamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='comentario_fechamento',
        ),
        migrations.AddField(
            model_name='comentario',
            name='fechamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('aberto', 'aberto'), ('andamento', 'andamento'), ('fechado', 'fechado')], default='aberto', max_length=10, verbose_name='Status'),
        ),
    ]
