# Generated by Django 4.2.5 on 2023-11-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_remove_ticket_comentario_fechamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comentario_fechamento',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Comentário de fechamento'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fechamento',
            field=models.BooleanField(default=False, verbose_name='Fechado'),
        ),
    ]
