# Generated by Django 4.2.5 on 2023-11-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_remove_ticket_comentario_fechamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fechamento',
        ),
    ]
