# Generated by Django 4.2.5 on 2023-09-09 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiomodel',
            name='numero_identificacao',
            field=models.PositiveIntegerField(help_text='Número de identificação do condomínio', unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=1, message='O número de identificação deve ter pelo menos 1 caractere.')], verbose_name='Número de Identificação'),
        ),
    ]
