# Generated by Django 4.2.5 on 2023-09-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_remove_ticket_condominio'),
        ('cadastro', '0002_alter_condominiomodel_numero_identificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nnumero_identificacao', models.PositiveIntegerField(help_text='Número de identificação do condomínio', unique=True, verbose_name='Número de Identificação')),
            ],
        ),
        migrations.DeleteModel(
            name='Condominiomodel',
        ),
    ]
