# Generated by Django 4.2.5 on 2023-09-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_condominio_delete_condominiomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='nome',
            field=models.CharField(blank=True, help_text='Infome o nome do Condominio', max_length=50, verbose_name='Nome do Condominio'),
        ),
    ]
