# Generated by Django 4.2.5 on 2023-09-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_condominio_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominio',
            old_name='nnumero_identificacao',
            new_name='numero_identificacao',
        ),
    ]
