# Generated by Django 4.2.5 on 2023-09-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_condominio_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Equipamento')),
                ('numero_serie', models.CharField(max_length=50, verbose_name='Número de Série')),
                ('data_instalacao', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
