# Generated by Django 4.2.5 on 2023-09-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_instalacao',
            field=models.DateField(blank=True, help_text='Exemplo de data: 01/01/2023', null=True, verbose_name='Data de Instalação'),
        ),
    ]
