# Generated by Django 4.2.5 on 2023-09-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_equipamento_data_instalacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='numero_identificacao',
            field=models.PositiveIntegerField(help_text='Número de identificação do condomínio', unique=True, verbose_name='Conta'),
        ),
    ]
