# Generated by Django 4.2.5 on 2023-09-14 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_condominio_numero_identificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='condominio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='cadastro.condominio', verbose_name='Condomínio'),
        ),
    ]
