# Generated by Django 4.2.5 on 2023-09-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_equipamento_condominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='data_compra',
            field=models.DateField(blank=True, help_text='Exemplo de data: 01/01/2023', null=True, verbose_name='Data de Compra'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_fim_garantia',
            field=models.DateField(blank=True, help_text='Exemplo de data: 01/01/2023', null=True, verbose_name='Data Fim de Garantia'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='dia_recebimento',
            field=models.DateField(blank=True, help_text='Exemplo de data: 01/01/2023', null=True, verbose_name='Dia de Recebimento'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='testado',
            field=models.BooleanField(default=False, verbose_name='Equipamento Testado'),
        ),
    ]
