# Generated by Django 4.2.5 on 2023-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_equipamento_data_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='endereco',
            field=models.CharField(blank=True, help_text='Infome o endereço do Condominio', max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='testado',
            field=models.BooleanField(default=False, verbose_name='Testado'),
        ),
    ]
