# Generated by Django 4.2.5 on 2023-09-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_condominio_endereco_alter_equipamento_testado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='endereco',
            field=models.CharField(blank=True, help_text='Infome o endereço', max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='nome',
            field=models.CharField(help_text='Infome o nome', max_length=50, verbose_name='Nome do Condominio'),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='numero_identificacao',
            field=models.PositiveIntegerField(help_text='Número de identificação', unique=True, verbose_name='Conta'),
        ),
    ]
