# Generated by Django 4.2.5 on 2023-09-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_alter_condominio_endereco_alter_condominio_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_fim_garantia',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim de Garantia'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Instalação'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='dia_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Dia de Recebimento'),
        ),
    ]
