# Generated by Django 4.2.5 on 2023-09-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_alter_equipamento_data_fim_garantia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
