# Generated by Django 4.2.5 on 2023-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_equipamento_descricao_alter_equipamento_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='data_compra',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='data_fim_garantia',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='dia_recebimento',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_instalacao',
            field=models.DateField(blank=True, help_text='Exemplo de data: 01/01/2023', null=True, verbose_name='Data de Instalação'),
        ),
    ]
