# Generated by Django 4.2.5 on 2023-10-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_remove_equipamento_data_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='descricao',
        ),
    ]
