# Generated by Django 4.2.5 on 2023-10-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_remove_equipamento_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código da Categoria')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criação Em')),
            ],
        ),
    ]
