# Generated by Django 4.2.5 on 2023-10-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_categoriaequipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='cadastro.categoriaequipamento', verbose_name='Categoria'),
        ),
    ]
