# Generated by Django 4.2.5 on 2023-11-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_equipamento_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaequipamento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Categoria equipamentos', 'verbose_name_plural': 'Categoria'},
        ),
    ]
