# Generated by Django 4.2.5 on 2023-11-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_alter_categoriaequipamento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaequipamento',
            name='equipamento',
        ),
    ]
